-- Clear existing certifications data
DELETE FROM certifications;

-- Insert demo certifications data
INSERT INTO certifications (id, title, issuer, date, "credentialId", image, description, skills, "verificationUrl", featured, "validUntil", level, "examScore") VALUES
('cert_1', 'AWS Certified Solutions Architect - Associate', 'Amazon Web Services', '2024', 'AWS-SAA-C03-2024-001', '/placeholder.svg?height=400&width=600', 'Validates expertise in designing distributed systems on AWS. This certification demonstrates the ability to design and deploy scalable, highly available, and fault-tolerant systems on Amazon Web Services. It covers architectural best practices, security implementation, cost optimization, and operational excellence.', ARRAY['AWS', 'Cloud Architecture', 'Security', 'Scalability', 'EC2', 'S3', 'VPC'], 'https://aws.amazon.com/verification', true, '2027', 'Associate', '892/1000'),

('cert_2', 'Google Cloud Professional Cloud Architect', 'Google Cloud', '2024', 'GCP-PCA-2024-002', '/placeholder.svg?height=400&width=600', 'Demonstrates ability to design, develop, and manage robust, secure, scalable, highly available, and dynamic solutions to drive business objectives. This certification validates skills in designing and planning cloud solution architecture, managing and provisioning cloud solution infrastructure, and ensuring solution and operations reliability.', ARRAY['Google Cloud', 'Kubernetes', 'Cloud Architecture', 'DevOps', 'Compute Engine', 'Cloud Storage'], 'https://cloud.google.com/certification/verify', true, '2026', 'Professional', '88%'),

('cert_3', 'Microsoft Azure Fundamentals', 'Microsoft', '2023', 'AZ-900-2023-003', '/placeholder.svg?height=400&width=600', 'Validates foundational knowledge of cloud services and how those services are provided with Microsoft Azure. This certification demonstrates understanding of cloud concepts, Azure services, Azure workloads, security and privacy in Azure, as well as Azure pricing and support.', ARRAY['Microsoft Azure', 'Cloud Fundamentals', 'Azure Services', 'Cloud Security'], 'https://docs.microsoft.com/en-us/learn/certifications/azure-fundamentals', false, '2026', 'Associate', '850/1000'),

('cert_4', 'Meta React Developer Certificate', 'Meta (Facebook)', '2023', 'META-RD-2023-004', '/placeholder.svg?height=400&width=600', 'Comprehensive React development skills certification covering modern React patterns, hooks, state management, testing, and performance optimization. This program demonstrates proficiency in building production-ready React applications with industry best practices.', ARRAY['React', 'JavaScript', 'Frontend Development', 'Testing', 'Redux', 'React Hooks'], 'https://developers.facebook.com/certification/verify', true, 'Lifetime', 'Professional', '95%'),

('cert_5', 'MongoDB Certified Developer Associate', 'MongoDB University', '2023', 'MDB-DEV-2023-005', '/placeholder.svg?height=400&width=600', 'Expertise in MongoDB database design and development. This certification validates skills in data modeling, aggregation pipelines, indexing strategies, performance optimization, and MongoDB application development best practices.', ARRAY['MongoDB', 'Database Design', 'Aggregation', 'Performance Optimization', 'NoSQL'], 'https://university.mongodb.com/certification/verify', false, '2026', 'Associate', '88%'),

('cert_6', 'Docker Certified Associate', 'Docker Inc.', '2022', 'DCA-2022-006', '/placeholder.svg?height=400&width=600', 'Container orchestration and Docker platform expertise. This certification demonstrates proficiency in containerization, Docker Swarm, security best practices, container lifecycle management, and Docker networking and storage.', ARRAY['Docker', 'Containerization', 'DevOps', 'Orchestration', 'Docker Swarm', 'Container Security'], 'https://docker.com/certification/verify', false, '2025', 'Associate', '82%'),

('cert_7', 'Certified Kubernetes Administrator (CKA)', 'Cloud Native Computing Foundation', '2022', 'CKA-2022-007', '/placeholder.svg?height=400&width=600', 'Kubernetes cluster administration and management certification. This hands-on certification validates the ability to perform the responsibilities of Kubernetes administrators including installation, configuration, management of production-grade Kubernetes clusters, troubleshooting, and networking.', ARRAY['Kubernetes', 'Container Orchestration', 'DevOps', 'Linux', 'Cluster Management', 'Networking'], 'https://cncf.io/certification/verify', true, '2025', 'Professional', '89%'),

('cert_8', 'GitHub Actions Certification', 'GitHub', '2023', 'GHA-2023-008', '/placeholder.svg?height=400&width=600', 'Demonstrates expertise in implementing CI/CD workflows using GitHub Actions. This certification covers workflow automation, deployment strategies, security best practices, and advanced GitHub Actions features for modern software development.', ARRAY['GitHub Actions', 'CI/CD', 'DevOps', 'Automation', 'Deployment', 'Workflow Management'], 'https://github.com/certification/verify', false, '2026', 'Professional', '91%'),

('cert_9', 'Vercel Frontend Cloud Certification', 'Vercel', '2023', 'VFC-2023-009', '/placeholder.svg?height=400&width=600', 'Validates expertise in deploying and optimizing frontend applications on Vercel platform. Covers Next.js deployment, edge functions, performance optimization, and modern frontend development practices with serverless architecture.', ARRAY['Vercel', 'Next.js', 'Frontend Deployment', 'Edge Functions', 'Performance Optimization'], 'https://vercel.com/certification/verify', false, '2026', 'Associate', '87%'),

('cert_10', 'Supabase Developer Certification', 'Supabase', '2024', 'SDB-2024-010', '/placeholder.svg?height=400&width=600', 'Demonstrates proficiency in building full-stack applications with Supabase. Covers database design, real-time subscriptions, authentication, edge functions, and modern backend-as-a-service development patterns.', ARRAY['Supabase', 'PostgreSQL', 'Real-time', 'Authentication', 'Backend-as-a-Service', 'Edge Functions'], 'https://supabase.com/certification/verify', true, '2027', 'Professional', '93%');
